#!/bin/bash

# shortcuts
alias e="$EDITOR" \
      v="$EDITOR"


# default arguments
alias valgrid="valgrid --leak-check=full --track-origins=yes --show-reachable=yes"
alias ls="ls -A -hN --group-directories-first"
alias mvn="mvn -gs \"$XDG_CONFIG_HOME/maven/settings.xml\""


# substitutions 
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"


# dotfiles
command -v git >/dev/null  && \
	alias config="git --git-dir=$HOME/.cfg/ --work-tree=$HOME"


# colors
alias ls="${BASH_ALIASES[ls]} --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"


# enable aliases with sudo
alias sudo="sudo "


