#!/bin/bash

# shortcuts
alias e="$EDITOR" \
      v="$EDITOR"

# default arguments
alias valgrid="valgrid --leak-check=full --track-origins=yes --show-reachable=yes"
alias ls="ls -A -hN --group-directories-first" \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"                        # use neovim instead of vim
command -v git >/dev/null  && alias config="git --git-dir=$HOME/.cfg/ --work-tree=$HOME"  # use config command for dotfiles git repo

# colors
alias ls="${BASH_ALIASES[ls]} --color=auto" \
      grep="grep --color=auto" \
      diff="diff --color=auto"

# enable aliases with sudo
alias sudo="sudo "


